#! /bin/bash
# collects Pareto points from all *.out files in the current directory,
# assuming the *.out files were generated by the minimization program
# and Pareto points are tagged with Pareto
# uses the script collectParetoPoints.py, assumed to be in ~/Git/LG-Local/scripts/

script=~/Git/LG-Local/scripts/collectParetoPoints.py

for file in *.out; do
    base=`basename $file`
    echo -n "$base,"
    grep "^Pareto" $file | cut -f 2 -d, | $script
done